{% set name = "abtem" %}
{% set version = "1.0.9" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/abtem-{{ version }}.tar.gz
  sha256: 440c38ed82f2591b0aabf64f549aaf22febf86ef9615dd16b9c3fcbdc1518a87

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.6.0
    - wheel
    - pip
  run:
    - tqdm
    - python >={{ python_min }},<3.12
    - numpy
    - pandas
    - matplotlib-base >=3.6
    - pyfftw
    - scipy
    - numba
    - dask-core >=2022.12.1,!=2025.12.*,!=2026.1.*
    - distributed
    - zarr
    - ase
    - threadpoolctl
    - tabulate
    - ipywidgets
    - ipympl

test:
  imports:
    - abtem
    - abtem.visualize
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jacobjma/abtem
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: ab initio Transmission Electron Microscopy

  description: |
    abTEM provides a Python API for running simulations of Transmission 
    Electron Microscopy images. It is written entirely in Python, which 
    enables easy integration with first-principles codes and analysis tools 
    accessible from Python, and allows for a simple and intuitive user 
    interface. The computationally demanding parts are implemented using 
    jit-compiled Numba code and high-performance libraries, maintaining
    speed while ensuring portability.
  doc_url: https://abtem.readthedocs.io
  dev_url: https://github.com/jacobjma/abtem

extra:
  recipe-maintainers:
    - jan-janssen
    - jacobjma
    - ericpre
