{% set name = "abtem" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/abtem-{{ version }}.tar.gz
  sha256: fc3a8a88e19d5cb6ac79af878ff96cf9365ee306cd26cb9244bdfb968425435f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ase
    - h5py
    - imageio
    - matplotlib-base
    - numba
    - numpy
    - psutil
    - pyfftw
    - python >=3.6
    - scipy
    - tqdm
    - dask
    - threadpoolctl
    - zarr
    - tabulate
    - traitlets
    - ipympl
    - ipywidgets
    - jupyterlab

test:
  imports:
    - abtem
    - abtem.visualize
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jacobjma/abtem
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: ab initio Transmission Electron Microscopy

  description: |
    abTEM provides a Python API for running simulations of Transmission 
    Electron Microscopy images. It is written entirely in Python, which 
    enables easy integration with first-principles codes and analysis tools 
    accessible from Python, and allows for a simple and intuitive user 
    interface. The computationally demanding parts are implemented using 
    jit-compiled Numba code and high-performance libraries, maintaining
    speed while ensuring portability.
  doc_url: https://abtem.readthedocs.io
  dev_url: https://github.com/jacobjma/abtem

extra:
  recipe-maintainers:
    - jan-janssen
    - jacobjma
    - ericpre
