{% set name = "abtem" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/abtem-{{ version }}.tar.gz
  sha256: 4beed2f5405a58b765587e3f87164c3214046eaeac2f7480c6232859b5f19996

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.9,<3.12
    - setuptools >=40.6.0
    - wheel
    - pip
  run:
    - python >=3.9,<3.12
    - numpy <2.0
    - pandas
    - matplotlib-base >=3.6
    - pyfftw
    - scipy
    - numba
    - dask-core >=2022.12.1
    - distributed
    - zarr
    - ase
    - threadpoolctl
    - tabulate
    - ipywidgets
    - ipympl

test:
  imports:
    - abtem
    - abtem.visualize
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jacobjma/abtem
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: ab initio Transmission Electron Microscopy

  description: |
    abTEM provides a Python API for running simulations of Transmission 
    Electron Microscopy images. It is written entirely in Python, which 
    enables easy integration with first-principles codes and analysis tools 
    accessible from Python, and allows for a simple and intuitive user 
    interface. The computationally demanding parts are implemented using 
    jit-compiled Numba code and high-performance libraries, maintaining
    speed while ensuring portability.
  doc_url: https://abtem.readthedocs.io
  dev_url: https://github.com/jacobjma/abtem

extra:
  recipe-maintainers:
    - jan-janssen
    - jacobjma
    - ericpre
