schema_version: 1

context:
  name: abtem
  version: "1.0.10"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/abtem-${{ version }}.tar.gz
  sha256: 30717db9d339aed03ad5238aa7504b75694481a455e2cfc95f1453f49583f3a2

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python 3.11.*
    - setuptools >=40.6.0
    - wheel
    - pip
  run:
    - tqdm
    - python >=${{ python_min }}
    - numpy >=2.0.0
    - pandas
    - matplotlib-base >=3.6
    - pyfftw
    - scipy
    - numba
    - dask-core >=2022.12.1,!=2025.12.*,!=2026.1.0,!=2026.1.1
    - distributed
    - zarr >=3.1
    - ase
    - threadpoolctl
    - tabulate
    - ipywidgets
    - ipympl

tests:
  - python:
      imports:
        - abtem
        - abtem.visualize
      pip_check: true
      python_version: ${{ python_min }}

about:
  license: GPL-3.0-only
  license_file: LICENSE
  summary: ab initio Transmission Electron Microscopy
  description: |
    abTEM provides a Python API for running simulations of Transmission
    Electron Microscopy images. It is written entirely in Python, which
    enables easy integration with first-principles codes and analysis tools
    accessible from Python, and allows for a simple and intuitive user
    interface. The computationally demanding parts are implemented using
    jit-compiled Numba code and high-performance libraries, maintaining
    speed while ensuring portability.
  homepage: https://github.com/jacobjma/abtem
  repository: https://github.com/jacobjma/abtem
  documentation: https://abtem.readthedocs.io

extra:
  recipe-maintainers:
    - jan-janssen
    - jacobjma
    - ericpre
